### ISSUE TITLE
[Meta] DNS routing for office 365

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#156]
James - do we want office 365 to handle the xxxxx@granitehr.com emails.  If so I can have Derek set it up.  

For Now Lets use the Following:
Call: 406-248-6178
Email: granitehr@aehr.org

![image](https://user-images.githubusercontent.com/425929/37218975-49a15a4c-237f-11e8-980d-213f04944b21.png)

**Comment by James1x0** [comment]
@groadifer Yeah, let's get Derek to set up a box for that. I'll need the DNS settings from him to route mail there.

**Comment by James1x0** [comment]
@groadifer any update on this?

**Comment by James1x0** [comment]
This is complete
