### ISSUE TITLE
Granite Testing

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#166]
I started back in today on some granite hr testing and my password wouldn't work and I also could not recover my password.   

Was database wiped and do I need to set up AMS company again or can you send me a recovery password link.  Thanks.

![image](https://user-images.githubusercontent.com/425929/38040602-16a75054-326d-11e8-9d5b-339303440a86.png)

**Comment by James1x0** [comment]
@groadifer Yeah, the password recovery needs set up. It says user not found, are you sure you used that email?

**Comment by groadifer** [comment]
@James1x0 I found the activation link and it was to that email?

![image](https://user-images.githubusercontent.com/425929/38045424-f15d09b2-3279-11e8-9e42-0fed0a5f8f69.png)

**Comment by James1x0** [comment]
@groadifer Ah, I just looked at the record and your email is all uppercase. It should have converted that to lower case when you signed up, so I'll file that as a bug. You should be able to log in now, I've changed the record to lower case.
