### ISSUE TITLE
Census Upload Error - XAPIToken

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#169]
![image](https://user-images.githubusercontent.com/425929/38113132-461c46f6-3361-11e8-80d4-576a273efc05.png)

**Comment by James1x0** [comment]
This should be fixed, but I don't think it's deployed, yet.
Bisect: https://github.com/associatedemployers/granite/commit/13cc229c536193fb35915921b3ba6ed208446602

**Comment by James1x0** [comment]
Deployed today, issue is confirmed fixed.
