### ISSUE TITLE
[Enhancement] New Company Landing/Information Page

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#184]
This is the screen when I log in for the first time as a new company.  Look nice but at some point we will probably want to work on a new Company Landing page with steps to set up your new company or at-least have a written handout for them to follow to successfully set up new company into Granite. 

![image](https://user-images.githubusercontent.com/425929/39883796-2440168e-5445-11e8-8fbd-5d5e9486ee1f.png)

**Comment by James1x0** [comment]
Good point. There are some first steps in the welcome email but I definitely agree with you.

**Comment by groadifer** [comment]
One idea to to pre- build a list of Action Items on within the Action Item Functionality and have it land on that page?

**Comment by JavaLavaMT** [comment]
add 3 cards Anatomy, employees, and settings. Anatomy will have a check for departments and a location added. Employees will check for an added employee. Settings will check to see if they visit the page.
