### ISSUE TITLE
[Feature] add support link

### ISSUE THREAD

**Issue by JavaLavaMT** [associatedemployers/granite#221]

**Comment by James1x0** [comment]
- [ ] Generate routes:
  - [ ] account/help
  - [ ] account/help/index
  - [ ] account/help/topic
    - [ ] Add parameter for url: `account/help/topic/:topic_slug`
*In an effort to extend this for future DB drivability, we'll use some fixture data. (as described below)*
- [ ] Add help.json to `app/config` (or .js)
- [ ] Add fixture articles to `app/config/help.json` in this format:
```
{
  "article-name-in-dasherized-case": {
    "title": "My Article Name",
    "body": "<p>Some HTML data here...</p>"
  },
  "article-name-in-dasherized-case-2": {
    "title": "My Article Name 2",
    "body": "<p>Some more HTML data here...</p>"
  }
}
```
- [ ] Use the above data in account/help/index to display as list as wireframed
- [ ] Use the above data via object `key` in account/help/topic to display a particular topic
  - [ ] Render triple curly body
- [ ] Add help link to side menu

**Comment by James1x0** [comment]
[Support wireframe rendered](https://sketch.cloud/s/vLOe3/p/support-link)
