### ISSUE TITLE
[Enhancement] Improve parser dictionary

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#240]
No rush on this one but you may want to check this out.  I think you would anticipate the Guessed Fields to work out better then it did. I think it was working last time we tried it but this time it didn't even guess that State was State or Zip was Zip?  I will convert the fields but for the customers I am sure we hope it guesses better then this.  Any thoughts?  Thanks,

![image](https://user-images.githubusercontent.com/425929/41254669-613c00d4-6d81-11e8-859b-c47ea1c7b44f.png)

**Comment by James1x0** [comment]
The parser definition for this is sort of sparse. We have a better dictionary over on slate-api, so we could steal from that.

Current definition:
```
[{
  "name.first":   [ "first name", "name first" ],
  "name.middle":  [ "middle name", "middle initial", "name middle", "mi", "m.i." ],
  "name.last":    [ "last name", "name last", "given name", "name given", "family name", "name family" ],
  "email":        [ "email", "email address", "webmail" ],
  "dateOfBirth":  [ "dob", "date of birth", "birth date" ],
  "hiredOn":      [ "hire date", "date of hire", "hired on", "hired" ],
  "terminatedOn": [ "termination date", "date of termination", "terminated on", "terminated", "termination" ]
}]
```
