### ISSUE TITLE
Initial Employee and HR Management Setup Emails and Links

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#318]
3 emails received.  First email is good but it could maybe better define the names and that clicking a link is required for the Employer but also the Employer needs to setup him/her self up as an employee.  
![image](https://user-images.githubusercontent.com/425929/45851533-a7ec6980-bcf8-11e8-9635-7a7bca8b8d83.png)

Second Email 
![image](https://user-images.githubusercontent.com/425929/45851580-e41fca00-bcf8-11e8-8885-a72b844ee719.png)

Third Email 
![image](https://user-images.githubusercontent.com/425929/45851607-0d405a80-bcf9-11e8-99f9-eae9f944ceed.png)

PROBLEM.  Following the signup on the third email.  It didn't work.  Does it conflict with the same email is used for the Employee Portal and HR Management Portal.   When trying to recover the password on the HR management portal I clicked link in password recover email but it wouldn't login.

![image](https://user-images.githubusercontent.com/425929/45851789-d6b70f80-bcf9-11e8-9474-34f25a790616.png)

**Comment by James1x0** [comment]
Third email probably just needs a www.

**Comment by James1x0** [comment]
This is now being tracked in an igneous issue. associatedemployers/igneous#111
