### ISSUE TITLE
[Feature] Hook up associated documents on assets & categories

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#336]
- [ ] new documents tag for filtering 
- [ ] filter documents based on tags  in account/assets/new
- [ ] way to upload a new document when creating a new asset (i.e. drop zone or file explorer) 
- [ ] ability to edit/remove documents assigned to categories or assets

**Comment by JavaLavaMT** [comment]
[] new documents tag for filtering 
[] filter documents based on tags  in account/assets/new
[] way to upload a new document when creating a new asset (i.e. drop zone or file explorer)
