### ISSUE TITLE
[Rollbar] [Bug] census custom field header cause rollbar

### ISSUE THREAD

**Issue by JavaLavaMT** [associatedemployers/granite#463]
when you upload a census and click a header and select 'custom fields' you get an error

https://rollbar.com/AMS/Granite/items/53/

**Comment by James1x0** [comment]
@JavaLavaMT Is this still a bug?

**Comment by JavaLavaMT** [comment]
> @JavaLavaMT Is this still a bug?

no, was fixed in a PR
