### ISSUE TITLE
[Bug] Campaign chart

### ISSUE THREAD

**Issue by petersonbrock** [associatedemployers/granite#466]
possibly a race condition with ember-cli-chart?

<img width="1677" alt="screen shot 2019-01-25 at 9 40 48 am" src="https://user-images.githubusercontent.com/32846657/51759446-79571480-2085-11e9-8fd9-c5a0c2efb1f9.png">

**Comment by James1x0** [comment]
Fixed via 57770ba8cc25fb0e20345b41654e81b8a5f530c9
