### ISSUE TITLE
[Bug] Link color in employee summary (dark text) is not perfect for every case

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#492]
In this case, readability is garbage. Let's find a better way to indicate a link and provide dark text.

![screen shot 2019-02-21 at 2 55 55 pm](https://user-images.githubusercontent.com/6146261/53204469-eb6d3b80-35e8-11e9-9bf5-60ffc46215b2.png)

**Comment by JavaLavaMT** [comment]
what if we just increased then number at which the "dark text" gets called true, that would give this background color show white text like so 

![image](https://user-images.githubusercontent.com/25805625/54548665-032cab00-496e-11e9-9e78-33f181ac369b.png)

**Comment by James1x0** [comment]
@JavaLavaMT Not necessarily the problem, although it does look better. I was more concerned about the actual blue color.
