### ISSUE TITLE
[Bug] Investigate failures with "employee_change-request" template

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#738]
On granite live db, search: `db.getCollection('notifications').find({ failures: { $gt: 0 } })`: there are 3 notifications that failed over and over for this template.

**Comment by JavaLavaMT** [comment]
@James1x0 fixed on associatedemployers/igneous#301
at https://github.com/associatedemployers/igneous/commit/cf357e56aea707780471ab1e8df959c1574116d2#diff-bedb54a72ffb84fec6479c8072344045R23
