### ISSUE TITLE
Asset add modal is buggy

### ISSUE THREAD

**Issue by jscottchapman** [associatedemployers/granite#88]
When onboarding an employee and you want to create stock for an asset item the modal is dimmed like the background and it doesn't seem to save the item.

**Comment by jscottchapman** [comment]
If there is a modal on the page and you delete the "pushable" class from that one <div> the problem goes away.

**Comment by James1x0** [comment]
But the menu probably fails to work, right?

**Comment by James1x0** [comment]
Using `detachable=true` remedies this issue.
