### ISSUE TITLE
[Bug] Social security input was removed in newest master, but used in a beneficiary form

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#892]
![Screen Shot 2020-12-02 at 1.44.20 PM.png](https://images.zenhubusercontent.com/5c9251f583c46e630dc1836b/a5ab8b49-abe7-465d-9c3a-d3f688159cdb)

**Comment by JavaLavaMT** [comment]
Issue moved to [associatedemployers/quartz #187](https://github.com/associatedemployers/quartz/issues/187) via [**ZenHub**](https://www.zenhub.com/)
